urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib.auth.views import logout
import django

from views import common, rest

import settings
django.get_version()
login_template_name = {'template_name' : 'accounts/login.html'}

urlpatterns = patterns('',

    #index
    (r'^$', common.index),
    (r'^index/$', common.index),

    #login
    (r'^login/$', common.method_splitter, {'get' : common.login_get, 'post' : common.login_post}),
    (r'account/$', common.method_splitter, {'get' : common.login_get, 'post' : common.login_post}),
    (r'account/login/$', common.method_splitter, {'get' : common.login_get, 'post' : common.login_post}),
    (r'^accounts/login/$',common.method_splitter, {'get' : common.login_get, 'post' : common.login_post}),

    #logout
    (r'^account/logout/$', logout, {'template_name' : 'accounts/logout.html'}),
    (r'^logout/$', logout)
    ,
    #profile
    (r'^account/profile', common.profile),

    #monitoring
    (r'analystics/$', common.test, {"template":"analystics/index.html"}),
    (r'cabinet/$', common.test, {"template":"cabinet/index.html"}),
    (r'reports/$', common.test, {"template":"reports/index.html"}),


    #company
    (r'^company/$', common.company_profile),
    (r'^company/profile/$', common.company_profile),
    (r'^company/employee/list/$', common.method_splitter, {'get' : common.employee_list, 'post' : None}),
    (r'^company/employee/list-rest/$', rest.get_employee_list), # получаем список сотрдунико в json
#    (r'^company/employee/get/(\d+)/$', common.method_splitter, {'get' : None, 'post' :rest.get_employee }),
    (r'^company/employee/save/$', common.method_splitter, {'get' : None, 'post' : rest.save_employee}),
    (r'^company/employee/refresh/$', rest.refresh_employee),
    (r'^company/employee/remove/(?P<employee_id>\w+)/$', rest.remove_employee),
    (r'^company/device/save/$', rest.save_device),
    (r'^company/device/refresh/$', rest.refresh_devices),
    (r'^company/device/remove/(?P<device_id>\w+)/$', rest.remove_device),


    #monitoring
    (r'^monitoring/$', common.monitoring),
#   (r'^monitoring/get-track/employee/(?P<employee_id>\w+)/date/(?P<date>\w+)/$', rest.get_track),
    (r'^monitoring/get-track/$', rest.get_track),
    (r'^monitoring/get-last-position', rest.get_last_position),
    (r'^monitoring/get-last-poisiton-by-employee', rest.get_last_position_by_employee),

    #logystics
    (r'^logistic/$', common.logistic),
    (r'^logistic/save-sale-point/$', rest.save_sale_point),
    (r'^logistic/get_sale_points/$', rest.get_sale_points),
    (r'^logistic/routing/$', common.method_splitter, {'get' : common.routing, 'post' : None}),
    #routing
    (r'^logistic/routing/add-sale-point-to-route/$', rest.add_sale_point_to_route),
    (r'^logistic/routing/update-waypoint/$', rest.update_waypoint),
    (r'^logistic/routing/get-current-route/$', rest.get_current_route),

    #hisotry
    (r'^history/(?P<employee_id>\w+)/$', common.history),
    (r'^history/$', common.history, {'employee_id' : None}),


    #register
    (r'^account/register/$', common.method_splitter, {'get' : common.register_get, 'post' : common.register_post }),
    (r'^register/$', common.method_splitter, {'get' : common.register_get, 'post' : common.register_post}),
    (r'^register/activate/$', common.activate, {'key' : None}),
    (r'^register/activate/(\w+)/$', common.activate),


    #temponary

    (r'^tour/$', common.test, {"template":"site/tour.html", 'item' : '#nav-tour'} ),
    (r'^pricing/$', common.test,{"template":"site/price.html", 'item' : '#nav-pricing'} ),
    (r'^why/$', common.test,{"template":"empty.html", 'item' : '#nav-why'} ),
    (r'^about/$', common.test,{"template":"site/about.html", 'item' : '#nav-about'} ),
#    (r'^api/', include('core.urls', 'core')),

    (r'^url404/$', common.url404),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
            }),
    )

forms.py
# -*- coding: utf-8 -*-
__author__ = 'warlock'

from django import forms
from views.form_validators import *

class LoginForm(forms.Form):
    username = forms.Field(widget=forms.TextInput(attrs={'class':'span4'}))
    password = forms.Field(widget=forms.PasswordInput(attrs={'class' : 'span4'}))
    remember_me = forms.Field(widget=forms.CheckboxInput(), required=False)


class RegisterForm(forms.Form):
    real_name = forms.CharField(
                                    max_length=256,
                                    error_messages={'required' : 'Обязательно для заполнения.'},
                                    validators=[full_name_validate]
    )
    email = forms.EmailField(
                                    max_length=256,
                                    error_messages={
                                                        'required' : 'Обязательно для заполнения.',
                                                        'invalid'  : 'Введите действительный e-mail адрес.'
                                                    },
                                    validators=[email_exists_validate]
    )
    password = forms.CharField(
                                    widget=forms.PasswordInput(),
                                    error_messages={'required' : 'Обязательно для заполнения.'})
    company_name = forms.CharField(
                                    max_length=256,
                                    error_messages={'required' : 'Обязательно для заполнения.'})
    company_phone = forms.Field(
                                    widget=forms.TextInput(),
                                    required=False,
                                    error_messages={'required' : 'Обязательно для заполнения.'})
#    promo_code = forms.CharField(
#                                    max_length=50,
#                                    validators=[promo_code_validate],
#                                    error_messages={'required' : 'Обязательно для заполнения.'})

class EmployeeForm(forms.Form):
    employee_frist_name = forms.CharField(
        max_length=256,
        error_messages={'required' : 'Поле Имя не заполнено.'},

    )

    employee_last_name = forms.CharField(
        max_length=256,
        error_messages={'required' : 'Поле Фамилия не заполнено.'}
    )

    employee_third_name = forms.CharField(
        max_length=256,
        error_messages={'required' : 'Поле Отчество не заполнено.'}
    )

    employee_phone = forms.CharField(
        max_length=50,
        required=False
    )

templates/accounts/activation.html
{% extends "base.html" %}

{% block nav-list %}

{% endblock %}

{% block content %}
    <div class="mt100">
    {% if key == None %}
        <p>На ваш e-mail было выслано письмо с активацией.</p>
    {% else %}
        {% if result %}
            Ваш аккаунт успешно активирован. Пожалуйста перейдите на страницу <a href="/account/login/">авторизации</a>.
        {% else %}
            По какой то причине данный ключ не может быть активирован. Попробуйте попытку позже или обратитесь в
            <a href="mailto:support@h-qub.ru">службу поддержки.</a>
        {% endif %}
    {% endif %}
    </div>

{% endblock %}

templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="span4 offset4">
            <form class="form-stacked login-margin-top-form" action="." method="post">
                {% csrf_token %}
                <fieldset>
                    <legend class="form-legend">Вход
                        <span><a href="/account/register">Регистрация </a></span>
                        <span><a href="/">Главная </a></span>
                    </legend>

                    <div class="row">
                        {% if err_message != None %}
                            <div class="alert alert-error fade in" data-dismiss="alert" style="margin-top: 20px;">
                                <a class="close">×</a>
                                <strong>{{ err_message }}</strong>
                            </div>
                        {% endif %}
                    </div>

                    <div style="padding-top: 30px; margin-left: 30px">
                        <div class="control-group">
                            <label class="control-label form-label" for="username">Эл. адрес (email)</label>
                            <div class="controls">
                                {{ form.username }}
                            </div>
                        </div>

                        <div class="clearfix">
                            <label class="control-label form-label" for="password">Пароль</label>
                            <div class="controls">
                              {{ form.password }}
                            </div>
                        </div>

                        <div class= "offset2 span3">
                            <a href="#">Забыли пароль?</a>
                        </div>
                    </div>
                    <div class="actions">
                        <div class="row">
                            <div class="span1">
                                <input class="btn btn-large btn-primary" name="commit" type="submit" value="Войти">
                            </div>
                        </div>
                    </div>
                </fieldset>
            </form>
        <div>
    </div>
{% endblock %}

templates/accounts/logout.html
{% extends 'base.html' %}

{% block content %}
    <div class="row log">
        <h2>Выход из системы</h2>
        <p>Thanks for spending some quality time with the Web site today.</p>
        <ul class="quick-links log1" >
            <li><a href="/index/">На главную</a></li>
            <li><a href="/account/login/">Авторизация</a></li>
        </ul>
    </div>

{% endblock %}

templates/accounts/profile.html
{% extends "base.html" %}

{% block advance-head %}
    <link rel="stylesheet" href="/media/css/profile/profile-style.css">
    <link rel="stylesheet" href="/media/css/ui-lightness/jquery-ui-1.8.18.custom.css">
{% endblock %}

{% block advance-script %}
    <script src="http://api-maps.yandex.ru/1.1/index.xml?key=ACH4Q08BAAAAEkI9BAIA_1NKy4GKnj0oAOequIqwsygI3fMAAAAAAAAAAABM5c3YPQW4ZU0M5yimzdYWroyCXQ==" type="text/javascript"></script>
    <script type="text/javascript" src="/media/js/jquery-ui-1.8.18.custom.min.js"></script>
    <script type="text/javascript">
        var global_nav_item_id = '#nav-profile';

    </script>
{% endblock %}

{% block nav-brand %}
    <a class="bs-brand" href="/">h-qub.ru</a>
{% endblock %}

{% block nav-list %}
    <ul class="nav">
         {% include "navigate/dash-menu-items.html" %}

         <li class="divider-vertical"></li>
         <li class="active">
            <a href="/account/profile">Профиль</a>
         </li>
    </ul>

    <ul class="nav pull-right">
        {% include "navigate/dash-advance-menu-items.html" %}
    </ul>
{% endblock %}


{% block content %}
  <div id="profile-container">
      <div id="tab" class="tabbable tabs-left">
          <ul class="nav nav-tabs">
              <li class="active"><a href="#lA" data-toggle="tab">Общие</a></li>
              <li><a href="#lB" data-toggle="tab">Настройки 1</a></li>
              <li><a href="#lC" data-toggle="tab">Настройки 2</a></li>
          </ul>
          <div class="tab-content">
              <div class="tab-pane active" id="lA">
                  <h3>Общие</h3>
                  
                  <p>В разработке.</p>
              </div>
              <div class="tab-pane" id="lB">
                  <h3>Настройки 1</h3>

                  <p>В разработке.</p>
              </div>
              <div class="tab-pane" id="lC">
                  <h3>Настройки 2</h3>

                  <p>В разработке.</p>
              </div>
          </div>
      </div>
  </div>

   <div id="dash-container">
       <div class="well" style="padding: 8px 0;">
           <ul class="nav nav-list">
               <li class="nav-header">Посещаемость</li>
                   <li class="active"><a href="#"><i class="icon-white icon-home"></i> Супервайзеры</a></li>
                   <li><a href="#"><i class="icon-book"></i> Торговые представители</a></li>
                   <li><a href="#"><i class="icon-pencil"></i> Текущее место рассположение</a></li>
               <li class="nav-header">GPS трекеры</li>
                   <li><a href="#"><i class="icon-user"></i> Информация о работе</a></li>
                   <li><a href="#"><i class="icon-cog"></i> Settings</a></li>
                   <li class="divider"></li>
                   <li><a href="#"><i class="icon-flag"></i> Help</a></li>

           </ul>
       </div> <!-- /well -->
   </div>
{% endblock %}


{% block footer %}

{% endblock %}

templates/accounts/register.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="span5 offset4">
            <form class="form-stacked register-margin-top-form" action="." method="post">
                {% csrf_token %}
                <fieldset>
                    <legend class="form-legend">Регистрация в системе
                    <span><a href="/account/login/">Войти →</a></span>
                    </legend>

                    <div class="row">
                        {% if is_valid == None or is_valid == True %}
                            <div class="alert alert-info register-alert-info">
                                <h4 style="margin-bottom: 10px;">Создайте бесплатную учетную запись</h4>
                                <p>
                                    Вы сможете в любой момент перейти на платную рассширенную подписку.
                                </p>
                            </div>
                        {% else %}
                            <div class="alert alert-error register-alert-error">
                                <a class="close" data-dismiss="alert">×</a>
                                <h4 style="margin-bottom: 10px;">Обнаружены следующие ошибки:</h4>
                                {% if error_message == None %}
                                    <p>Проверьте что отмеченные поля заполнены правильными значениями.</p>
                                {% else %}
                                    <p>{{ error_message }}</p>
                                {% endif %}
                            </div>
                        {% endif %}
                    </div>
                    <div class="control-group">
                        <label class="contorl-label form-label" for="id_real_name">Ваше полное имя:</label>

                        {% if form.errors.real_name != None  %}
                            <span class="label label-important">{{ form.errors.real_name.0 }}</span>
                        {% endif %}

                        <div class="controls">
                            {{ form.real_name }}
                            <p class="register-help-block">Обязательное. Введите ваши <strong>фамилию</strong> и <strong>имя.</strong></p>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="contorl-label form-label" for="id_email">Эл. почта (e-mail):</label>

                        {% if form.errors.email != None  %}
                            <span class="label label-important">{{ form.errors.email.0 }}</span>
                        {% endif %}

                        <div class="controls">
                            {{ form.email }}
                            <p class="register-help-block">Обязательный. На этот адрес будет выслано письмо для активации.</p>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="contorl-label form-label" for="id_password">Создать пароль:</label>

                        {% if form.errors.password != None  %}
                            <span class="label label-important">{{ form.errors.password.0 }}</span>
                        {% endif %}

                        <div class="controls">
                           {{ form.password }}
                            <p class="register-help-block">Обязательный.</p>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="contorl-label form-label" for="id_password_repeat">Повторите пароль:</label>

                        {% if form.errors.password != None  %}
                            <span class="label label-important">{{ form.errors.password.0 }}</span>
                        {% endif %}

                        <div class="controls">
                            {{ form.password }}
                            <p class="register-help-block">Обязательный.</p>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="contorl-label form-label" for="id_company_name">Название организации:</label>

                        {% if form.errors.company_name != None  %}
                            <span class="label label-important">{{ form.errors.company_name.0 }}</span>
                        {% endif %}

                        <div class="controls">
                            {{ form.company_name }}
                            <p class="register-help-block">Обязательный.</p>
                        </div>
                    </div>
                    
                    <div class="control-group">
                        <label class="control-label form-label" for="id_company_phone">Контактный телефон:</label>

                        {% if form.errors.company_phone != None  %}
                            <span class="label label-important">{{ form.errors.company_phone.0 }}</span>
                        {% endif %}

                        <div class="controls">
                            {{ form.company_phone }}
                            <p class="register-help-block">Контактный телефон. Необязательный.</p>
                        </div>
                    </div>


{#                    <div class="control-group">#}
{#                        <label class="control-label form-label" for="id_promo_code">Промо код:</label>#}
{##}
{#                        {% if form.errors.promo_code != None  %}#}
{#                            <span class="label label-important">{{ form.errors.promo_code.0}}</span>#}
{#                        {% endif %}#}
{##}
{#                        <div class="controls">#}
{#                            {{ form.promo_code }}#}
{#                            <p class="register-help-block">Проект находится в стадии разработки. Регистрация ограничена.</p>#}
{#                        </div>#}
{#                    </div>#}

                    <div class="actions register-actions">
                        <div class="alert alert-info register-alert-term-info">Зарегистрировавшись, вы принимаете <strong>наши</strong>
                            <a href="#">условия соглашения</a> и <a href="#">политики безопасности</a>.</div>
                        <input class="btn btn-large btn-primary" name="commit" type="submit" value="Зарегистрироваться">
                    </div>


                    <p class="ar">Уже есть учетная запись? <a href="account/login/">Войдите здесь →</a></p>
                </fieldset>
            </form>

            <p class="ac">
                <small>
                    Нужна помощь?
                    <a href="#" rel="facebox">Тех. поддержка</a>
                    &nbsp;
                    |
                    &nbsp;
                    <a href="#">Выслать подтверждение инструкции здесь →</a>
                </small>
            </p>
        </div>
    </div>
{% endblock %}

templates/accounts/settings.html
{% extends 'base.html' %}